<b>1<b/> Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np

In [4]:
vec_1 = np.arange(1,11,1)
print(vec_2)

[ 1  2  3  4  5  6  7  8  9 10]


<b>2<b/> Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [11]:
mat_2 = np.zeros((3, 3), dtype=int)
print(mat_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


<b>3<b/> Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [5]:
mat_3 = np.random.randint(0,11, size=(5,5),dtype=int)
print(mat_3)

[[ 8  1  1  1  9]
 [ 7  2 10  9  9]
 [ 9  2  1  8  2]
 [10  2  4  7  4]
 [ 1 10  7  2  1]]


<b>4<b/> Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [8]:
mat_4 = np.random.randn(4, 4) 
print(mat_4)

[[ 0.34561669 -0.40620024 -2.19420058  1.11589441]
 [-0.74303926  0.2555443   0.49060846 -1.68934473]
 [-0.01862036 -0.30779192 -0.47112287  0.22755254]
 [-0.944569   -0.80821294  1.16300038  0.26064583]]


In [10]:
np.isreal(mat_4)


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

<b>5<b/> Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [17]:
vec_1 = np.random.randint(0,10,5)
vec_2 = np.random.randint(0,10,5)
print(vec_1)
print(vec_2)
print(vec_1+vec_2)
print(vec_1-vec_2)
print(vec_1*vec_2)

[1 1 8 2 1]
[2 7 4 3 1]
[ 3  8 12  5  2]
[-1 -6  4 -1  0]
[ 2  7 32  6  1]


<b>6<b/> Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [21]:
vec_3 = np.random.random(7)
vec_4 = np.random.random(7)
print(vec_3)
print(vec_4)
np.dot(vec_3,vec_4)

[0.0345447  0.63032417 0.61668205 0.84454432 0.86529279 0.5842133
 0.74701027]
[0.66665756 0.37780769 0.24741123 0.01129001 0.82513614 0.46937209
 0.65552728]


1.9011631696493734

<b>7<b/> Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [24]:
mat_61 = np.random.randint(0,10, size=(2,2),dtype=int)
mat_62 = np.random.randint(0,10, size=(2,3),dtype=int)
print(mat_61)
print(mat_61)
print(np.dot(mat_61, mat_62))

[[0 4]
 [5 7]]
[[0 4]
 [5 7]]
[[24 24 36]
 [57 72 63]]


<b>8<b/>  Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [6]:
mat_8 = np.random.randint(0,11, size=(3,3),dtype=int)
print(mat_8)
print(np.linalg.inv(mat_8))

[[6 4 1]
 [1 4 7]
 [9 9 1]]
[[ 0.44360902 -0.03759398 -0.18045113]
 [-0.46616541  0.02255639  0.30827068]
 [ 0.20300752  0.13533835 -0.15037594]]


<b>9<b/> Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [33]:
mat_9 = np.random.rand(4,4)
print(mat_9)
print(mat_9.T)

[[0.4732005  0.59297518 0.61299538 0.51049342]
 [0.49482343 0.53491849 0.89515879 0.93660621]
 [0.04571437 0.11008803 0.18721103 0.60020014]
 [0.91804157 0.97956291 0.31400436 0.00345869]]
[[0.4732005  0.49482343 0.04571437 0.91804157]
 [0.59297518 0.53491849 0.11008803 0.97956291]
 [0.61299538 0.89515879 0.18721103 0.31400436]
 [0.51049342 0.93660621 0.60020014 0.00345869]]


<b>10<b/> Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.



In [7]:
mat_10 = np.random.randint(0,11, size=(3,4),dtype=int)
vec_10 = np.random.randint(0,11, size=(4),dtype=int)
print(np.dot(mat_10,vec_10))

[140 170  58]


<b>11<b/> Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.    

In [35]:
mat_11 = np.random.rand(2,3)
vec_11 = np.random.rand(3)
print(np.dot(mat_11,vec_11))

[1.21428108 1.29155732]


<b>12<b/> Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [8]:
mat_121 = np.random.randint(0,11, size=(2,2),dtype=int)
mat_122 = np.random.randint(0,11, size=(2,2),dtype=int)
print(mat_121*mat_122)

[[ 0  0]
 [20  6]]


<b>13<b/> Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.



In [9]:
mat_131 = np.random.randint(0,11, size=(2,2),dtype=int)
mat_132 = np.random.randint(0,11, size=(2,2),dtype=int)
print(mat_131)
print(mat_132)
print(np.dot(mat_131,mat_132))

[[ 0  7]
 [10  7]]
[[7 3]
 [5 7]]
[[ 35  49]
 [105  79]]


<b>14<b/> Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [10]:
mat_14 = np.random.randint(0,101, size=(5,5),dtype=int)
print(mat_14.sum())

1185


<b>15<b/> Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.


In [11]:
mat_151 = np.random.randint(0,11, size=(4,4),dtype=int)
mat_152 = np.random.randint(0,11, size=(4,4),dtype=int)
print(mat_151-mat_152)

[[-2 -1  7 -3]
 [-6  2 -8  2]
 [ 3 -2  1  3]
 [ 0  0  6  2]]


<b>16<b/> Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [42]:
mat_16 = np.random.rand(3,3)
print(mat_16)

[[0.80818364 0.57599343 0.23054092]
 [0.64693347 0.93809064 0.40387223]
 [0.03702665 0.20753737 0.24206316]]


In [52]:
elvec1=(mat_16[0,0]+mat_16[0,1]+mat_16[0,2])
print(elvec1)
elvec2=(mat_16[1,0]+mat_16[1,1]+mat_16[1,2])
print(elvec2)
elvec3=(mat_16[2,0]+mat_16[2,1]+mat_16[2,2])
print(elvec3)
vec16 = np.array([elvec1, elvec2,elvec3])
print(vec16)

1.61471798745498
1.9888963412941423
0.48662717342841577
[1.61471799 1.98889634 0.48662717]


<b>17<b/> Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [16]:
mat_17 = np.random.randint(100, size=(3,4),dtype=int)
print(mat_17)
mat_171 = np.power((mat_17),2)
print(mat_171)

[[52 62 59 37]
 [58 47 84 88]
 [77 96 46 11]]
[[2704 3844 3481 1369]
 [3364 2209 7056 7744]
 [5929 9216 2116  121]]


<b>18<b/> Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [12]:
vec_18 = np.random.randint(0,51, size=(4),dtype=int)
print(vec_18)

[13 29  9  1]


In [64]:
np.sqrt(vec_18)

array([4.35889894, 4.79583152, 6.40312424, 5.74456265])